# Generated by Django 5.1.6 on 2025-03-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_aspect', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_quartier', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aborder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarite', models.CharField(blank=True, max_length=50)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aspect')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_origine', models.CharField(blank=True, max_length=100)),
                ('contenu', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('note_global', models.IntegerField(blank=True, null=True)),
                ('aspects', models.ManyToManyField(blank=True, through='core.Aborder', to='core.aspect')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.medecin')),
            ],
        ),
        migrations.AddField(
            model_name='aborder',
            name='commentaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.commentaire'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quartier'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
