# Generated by Django 5.1.6 on 2025-03-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aspect_medecin_quartier_aborder_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aborder',
            name='polarite',
            field=models.CharField(blank=True, choices=[('Positif', 'Positif'), ('Négatif', 'Négatif'), ('Neutre', 'Neutre')], max_length=50),
        ),
    ]
