# Generated by Django 5.1.6 on 2025-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aborder_polarite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='aspects',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='note_global',
        ),
        migrations.AlterField(
            model_name='aborder',
            name='polarite',
            field=models.CharField(blank=True, choices=[('Positif', 'Positif'), ('Negatif', 'Negatif')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='source_origine',
            field=models.CharField(default='Inconnu', max_length=255),
        ),
        migrations.DeleteModel(
            name='Quartier',
        ),
    ]
