# Generated by Django 5.1.6 on 2025-04-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_medecin_quartier_remove_commentaire_aspects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='aborder',
            unique_together={('commentaire', 'aspect')},
        ),
        migrations.AddField(
            model_name='medecin',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='core.quartier'),
        ),
    ]
